spring: 
 profiles: 
  active: dev
---
spring: 
 profiles: dev
 application: 
  name: microservicecloud-config-atguigu-dev
---
spring: 
 profiles: test
 applicaion:
  name: microservicecloud-config-atguigu-test